2021-05-18 11:25:22,163 INFO    MainThread:173586 [wandb_setup.py:_flush():69] setting env: {}
2021-05-18 11:25:22,163 INFO    MainThread:173586 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-18 11:25:22,163 INFO    MainThread:173586 [wandb_init.py:_log_setup():336] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/American-Sign-Language-Recognition/wandb/run-20210518_112522-3vbd81mz/logs/debug.log
2021-05-18 11:25:22,163 INFO    MainThread:173586 [wandb_init.py:_log_setup():337] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/American-Sign-Language-Recognition/wandb/run-20210518_112522-3vbd81mz/logs/debug-internal.log
2021-05-18 11:25:22,164 INFO    MainThread:173586 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fdfa7dbdf28>
2021-05-18 11:25:22,164 INFO    MainThread:173586 [wandb_init.py:init():369] calling init triggers
2021-05-18 11:25:22,164 INFO    MainThread:173586 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-18 11:25:22,164 INFO    MainThread:173586 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 3kmqzsrw
2021-05-18 11:25:22,165 INFO    MainThread:173586 [wandb_run.py:finish():1208] finishing run ranuga-d/Sign-Language-Recognition/3kmqzsrw
2021-05-18 11:25:22,165 INFO    MainThread:173586 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-18 11:25:22,165 INFO    MainThread:173586 [wandb_run.py:_restore():1507] restore
2021-05-18 11:25:22,169 INFO    MainThread:173586 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 724
  total_bytes: 724
}

2021-05-18 11:25:22,994 INFO    MainThread:173586 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 724
  total_bytes: 724
}

2021-05-18 11:25:23,905 INFO    MainThread:173586 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 724
  total_bytes: 17540
}

2021-05-18 11:25:24,008 INFO    MainThread:173586 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6474
  total_bytes: 17540
}

2021-05-18 11:25:24,110 INFO    MainThread:173586 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6774
  total_bytes: 17540
}

2021-05-18 11:25:24,212 INFO    MainThread:173586 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6774
  total_bytes: 17540
}

2021-05-18 11:25:24,314 INFO    MainThread:173586 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6774
  total_bytes: 17540
}

2021-05-18 11:25:24,416 INFO    MainThread:173586 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6774
  total_bytes: 17540
}

2021-05-18 11:25:24,518 INFO    MainThread:173586 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6774
  total_bytes: 17540
}

2021-05-18 11:25:24,619 INFO    MainThread:173586 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 11:25:24,721 INFO    MainThread:173586 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 11:25:24,822 INFO    MainThread:173586 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 11:25:24,924 INFO    MainThread:173586 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 11:25:25,025 INFO    MainThread:173586 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 11:25:25,127 INFO    MainThread:173586 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 11:25:25,229 INFO    MainThread:173586 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 11:25:25,331 INFO    MainThread:173586 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 11:25:25,432 INFO    MainThread:173586 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 11:25:26,790 INFO    MainThread:173586 [wandb_run.py:_show_files():1879] logging synced files
2021-05-18 11:25:26,795 INFO    MainThread:173586 [wandb_init.py:init():418] starting backend
2021-05-18 11:25:26,795 INFO    MainThread:173586 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-18 11:25:26,798 INFO    MainThread:173586 [backend.py:ensure_launched():132] starting backend process...
2021-05-18 11:25:26,840 INFO    MainThread:173586 [backend.py:ensure_launched():137] started backend process with pid: 190946
2021-05-18 11:25:26,841 INFO    MainThread:173586 [wandb_init.py:init():423] backend started and connected
2021-05-18 11:25:26,856 INFO    MainThread:173586 [wandb_init.py:init():465] updated telemetry
2021-05-18 11:25:26,857 INFO    MainThread:173586 [wandb_init.py:init():484] communicating current version
2021-05-18 11:25:27,792 INFO    MainThread:173586 [wandb_init.py:init():489] got version response 
2021-05-18 11:25:27,792 INFO    MainThread:173586 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-18 11:25:28,682 INFO    MainThread:173586 [wandb_init.py:init():522] starting run threads in backend
2021-05-18 11:25:33,687 INFO    MainThread:173586 [wandb_run.py:_console_start():1565] atexit reg
2021-05-18 11:25:33,687 INFO    MainThread:173586 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.WRAP
2021-05-18 11:25:33,687 INFO    MainThread:173586 [wandb_run.py:_redirect():1455] Wrapping output streams.
2021-05-18 11:25:33,687 INFO    MainThread:173586 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-18 11:25:33,687 INFO    MainThread:173586 [wandb_init.py:init():546] run started, returning control to user process
2021-05-18 11:25:35,429 INFO    MainThread:173586 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-18 11:25:35,429 INFO    MainThread:173586 [jupyter.py:save_ipynb():268] looking for notebook: main.ipynb
2021-05-18 11:25:36,168 INFO    MainThread:173586 [wandb_init.py:_pause_backend():253] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7fdfa7d8cf28>
2021-05-18 11:25:51,025 INFO    MainThread:173586 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-18 11:25:51,067 INFO    MainThread:173586 [wandb_setup.py:_flush():69] setting env: {}
2021-05-18 11:25:51,068 INFO    MainThread:173586 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-18 11:25:51,068 INFO    MainThread:173586 [wandb_init.py:_log_setup():336] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/American-Sign-Language-Recognition/wandb/run-20210518_112551-24fxghjf/logs/debug.log
2021-05-18 11:25:51,068 INFO    MainThread:173586 [wandb_init.py:_log_setup():337] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/American-Sign-Language-Recognition/wandb/run-20210518_112551-24fxghjf/logs/debug-internal.log
2021-05-18 11:25:51,068 INFO    MainThread:173586 [wandb_init.py:init():369] calling init triggers
2021-05-18 11:25:51,068 INFO    MainThread:173586 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-18 11:25:51,068 INFO    MainThread:173586 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 3vbd81mz
2021-05-18 11:25:51,070 INFO    MainThread:173586 [wandb_run.py:finish():1208] finishing run ranuga-d/Sign-Language-Recognition/3vbd81mz
