2021-05-18 09:52:09,776 INFO    MainThread:96109 [wandb_setup.py:_flush():69] setting env: {}
2021-05-18 09:52:09,776 INFO    MainThread:96109 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-18 09:52:09,776 INFO    MainThread:96109 [wandb_init.py:_log_setup():336] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/American-Sign-Language-Recognition/wandb/run-20210518_095209-3agwf23i/logs/debug.log
2021-05-18 09:52:09,776 INFO    MainThread:96109 [wandb_init.py:_log_setup():337] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/American-Sign-Language-Recognition/wandb/run-20210518_095209-3agwf23i/logs/debug-internal.log
2021-05-18 09:52:09,777 INFO    MainThread:96109 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f264b312b38>
2021-05-18 09:52:09,777 INFO    MainThread:96109 [wandb_init.py:init():369] calling init triggers
2021-05-18 09:52:09,777 INFO    MainThread:96109 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-18 09:52:09,777 INFO    MainThread:96109 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 1xbu95xs
2021-05-18 09:52:09,778 INFO    MainThread:96109 [wandb_run.py:finish():1208] finishing run ranuga-d/Sign-Language-Recognition/1xbu95xs
2021-05-18 09:52:09,778 INFO    MainThread:96109 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-18 09:52:09,779 INFO    MainThread:96109 [wandb_run.py:_restore():1507] restore
2021-05-18 09:52:09,784 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 724
  total_bytes: 724
}

2021-05-18 09:52:10,777 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 724
  total_bytes: 724
}

2021-05-18 09:52:11,632 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 724
  total_bytes: 17540
}

2021-05-18 09:52:13,015 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11825
  total_bytes: 17540
}

2021-05-18 09:52:13,117 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11825
  total_bytes: 17540
}

2021-05-18 09:52:13,219 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11825
  total_bytes: 17540
}

2021-05-18 09:52:13,321 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11825
  total_bytes: 17540
}

2021-05-18 09:52:13,422 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17538
  total_bytes: 17540
}

2021-05-18 09:52:13,525 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17538
  total_bytes: 17540
}

2021-05-18 09:52:13,627 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:52:13,729 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:52:13,831 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:52:13,932 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:52:14,034 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:52:14,135 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:52:14,237 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:52:15,528 INFO    MainThread:96109 [wandb_run.py:_show_files():1879] logging synced files
2021-05-18 09:52:15,532 INFO    MainThread:96109 [wandb_init.py:init():418] starting backend
2021-05-18 09:52:15,532 INFO    MainThread:96109 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-18 09:52:15,535 INFO    MainThread:96109 [backend.py:ensure_launched():132] starting backend process...
2021-05-18 09:52:15,568 INFO    MainThread:96109 [backend.py:ensure_launched():137] started backend process with pid: 101499
2021-05-18 09:52:15,569 INFO    MainThread:96109 [wandb_init.py:init():423] backend started and connected
2021-05-18 09:52:15,578 INFO    MainThread:96109 [wandb_init.py:init():465] updated telemetry
2021-05-18 09:52:15,579 INFO    MainThread:96109 [wandb_init.py:init():484] communicating current version
2021-05-18 09:52:16,484 INFO    MainThread:96109 [wandb_init.py:init():489] got version response 
2021-05-18 09:52:16,484 INFO    MainThread:96109 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-18 09:52:17,328 INFO    MainThread:96109 [wandb_init.py:init():522] starting run threads in backend
2021-05-18 09:52:22,334 INFO    MainThread:96109 [wandb_run.py:_console_start():1565] atexit reg
2021-05-18 09:52:22,334 INFO    MainThread:96109 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.WRAP
2021-05-18 09:52:22,334 INFO    MainThread:96109 [wandb_run.py:_redirect():1455] Wrapping output streams.
2021-05-18 09:52:22,334 INFO    MainThread:96109 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-18 09:52:22,335 INFO    MainThread:96109 [wandb_init.py:init():546] run started, returning control to user process
2021-05-18 09:52:23,954 INFO    MainThread:96109 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-18 09:52:23,954 INFO    MainThread:96109 [jupyter.py:save_ipynb():268] looking for notebook: main.ipynb
2021-05-18 09:52:25,782 INFO    MainThread:96109 [wandb_init.py:_pause_backend():253] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7f2649a410f0>
2021-05-18 09:52:36,810 INFO    MainThread:96109 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-18 09:52:36,812 INFO    MainThread:96109 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-18 09:52:36,812 INFO    MainThread:96109 [jupyter.py:save_ipynb():268] looking for notebook: main.ipynb
2021-05-18 09:52:37,495 INFO    MainThread:96109 [wandb_init.py:_pause_backend():253] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7f264ab23780>
2021-05-18 09:52:37,671 INFO    MainThread:96109 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-18 09:52:37,712 INFO    MainThread:96109 [wandb_setup.py:_flush():69] setting env: {}
2021-05-18 09:52:37,713 INFO    MainThread:96109 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-18 09:52:37,713 INFO    MainThread:96109 [wandb_init.py:_log_setup():336] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/American-Sign-Language-Recognition/wandb/run-20210518_095237-q38hqubh/logs/debug.log
2021-05-18 09:52:37,713 INFO    MainThread:96109 [wandb_init.py:_log_setup():337] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/American-Sign-Language-Recognition/wandb/run-20210518_095237-q38hqubh/logs/debug-internal.log
2021-05-18 09:52:37,713 INFO    MainThread:96109 [wandb_init.py:init():369] calling init triggers
2021-05-18 09:52:37,713 INFO    MainThread:96109 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-18 09:52:37,713 INFO    MainThread:96109 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 3agwf23i
2021-05-18 09:52:37,714 INFO    MainThread:96109 [wandb_run.py:finish():1208] finishing run ranuga-d/Sign-Language-Recognition/3agwf23i
