2021-05-18 09:48:08,780 INFO    MainThread:96109 [wandb_setup.py:_flush():69] setting env: {}
2021-05-18 09:48:08,780 INFO    MainThread:96109 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-18 09:48:08,780 INFO    MainThread:96109 [wandb_init.py:_log_setup():336] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/American-Sign-Language-Recognition/wandb/run-20210518_094808-1mp7iodj/logs/debug.log
2021-05-18 09:48:08,780 INFO    MainThread:96109 [wandb_init.py:_log_setup():337] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/American-Sign-Language-Recognition/wandb/run-20210518_094808-1mp7iodj/logs/debug-internal.log
2021-05-18 09:48:08,780 INFO    MainThread:96109 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f2649a72b70>
2021-05-18 09:48:08,780 INFO    MainThread:96109 [wandb_init.py:init():369] calling init triggers
2021-05-18 09:48:08,781 INFO    MainThread:96109 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-18 09:48:08,781 INFO    MainThread:96109 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 35a1cwd9
2021-05-18 09:48:08,782 INFO    MainThread:96109 [wandb_run.py:finish():1208] finishing run ranuga-d/Sign-Language-Recognition/35a1cwd9
2021-05-18 09:48:08,782 INFO    MainThread:96109 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-18 09:48:08,782 INFO    MainThread:96109 [wandb_run.py:_restore():1507] restore
2021-05-18 09:48:08,786 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 724
  total_bytes: 724
}

2021-05-18 09:48:09,547 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 724
  total_bytes: 724
}

2021-05-18 09:48:10,389 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 724
  total_bytes: 6772
}

2021-05-18 09:48:11,221 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 724
  total_bytes: 17540
}

2021-05-18 09:48:11,324 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6437
  total_bytes: 17540
}

2021-05-18 09:48:11,427 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6476
  total_bytes: 17540
}

2021-05-18 09:48:11,529 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6476
  total_bytes: 17540
}

2021-05-18 09:48:11,631 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6476
  total_bytes: 17540
}

2021-05-18 09:48:11,732 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6476
  total_bytes: 17540
}

2021-05-18 09:48:11,834 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6476
  total_bytes: 17540
}

2021-05-18 09:48:11,936 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17242
  total_bytes: 17540
}

2021-05-18 09:48:12,038 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17242
  total_bytes: 17540
}

2021-05-18 09:48:12,140 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17242
  total_bytes: 17540
}

2021-05-18 09:48:12,241 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:48:12,344 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:48:12,446 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:48:12,547 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:48:12,649 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:48:12,751 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:48:12,852 INFO    MainThread:96109 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17540
  total_bytes: 17540
}

2021-05-18 09:48:14,154 INFO    MainThread:96109 [wandb_run.py:_show_files():1879] logging synced files
2021-05-18 09:48:14,159 INFO    MainThread:96109 [wandb_init.py:init():418] starting backend
2021-05-18 09:48:14,159 INFO    MainThread:96109 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-18 09:48:14,163 INFO    MainThread:96109 [backend.py:ensure_launched():132] starting backend process...
2021-05-18 09:48:14,193 INFO    MainThread:96109 [backend.py:ensure_launched():137] started backend process with pid: 98457
2021-05-18 09:48:14,194 INFO    MainThread:96109 [wandb_init.py:init():423] backend started and connected
2021-05-18 09:48:14,204 INFO    MainThread:96109 [wandb_init.py:init():465] updated telemetry
2021-05-18 09:48:14,204 INFO    MainThread:96109 [wandb_init.py:init():484] communicating current version
2021-05-18 09:48:15,131 INFO    MainThread:96109 [wandb_init.py:init():489] got version response 
2021-05-18 09:48:15,131 INFO    MainThread:96109 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-18 09:48:16,153 INFO    MainThread:96109 [wandb_init.py:init():522] starting run threads in backend
2021-05-18 09:48:21,158 INFO    MainThread:96109 [wandb_run.py:_console_start():1565] atexit reg
2021-05-18 09:48:21,159 INFO    MainThread:96109 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.WRAP
2021-05-18 09:48:21,159 INFO    MainThread:96109 [wandb_run.py:_redirect():1455] Wrapping output streams.
2021-05-18 09:48:21,159 INFO    MainThread:96109 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-18 09:48:21,159 INFO    MainThread:96109 [wandb_init.py:init():546] run started, returning control to user process
2021-05-18 09:48:22,780 INFO    MainThread:96109 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-18 09:48:22,780 INFO    MainThread:96109 [jupyter.py:save_ipynb():268] looking for notebook: main.ipynb
2021-05-18 09:48:23,482 INFO    MainThread:96109 [wandb_init.py:_pause_backend():253] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7f2652806ba8>
2021-05-18 09:48:47,307 INFO    MainThread:96109 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-18 09:48:47,348 INFO    MainThread:96109 [wandb_setup.py:_flush():69] setting env: {}
2021-05-18 09:48:47,348 INFO    MainThread:96109 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-18 09:48:47,348 INFO    MainThread:96109 [wandb_init.py:_log_setup():336] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/American-Sign-Language-Recognition/wandb/run-20210518_094847-1xbu95xs/logs/debug.log
2021-05-18 09:48:47,349 INFO    MainThread:96109 [wandb_init.py:_log_setup():337] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/American-Sign-Language-Recognition/wandb/run-20210518_094847-1xbu95xs/logs/debug-internal.log
2021-05-18 09:48:47,349 INFO    MainThread:96109 [wandb_init.py:init():369] calling init triggers
2021-05-18 09:48:47,349 INFO    MainThread:96109 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-18 09:48:47,349 INFO    MainThread:96109 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 1mp7iodj
2021-05-18 09:48:47,350 INFO    MainThread:96109 [wandb_run.py:finish():1208] finishing run ranuga-d/Sign-Language-Recognition/1mp7iodj
